import {Geist, Geist_Mono, Sour_Gummy} from "next/font/google";
import "./globals.css";
import Header from "@/app/_components/Header";

const geistSans = Geist({
    variable: "--font-geist-sans",
    subsets: ["latin"],
});

const geistMono = Geist_Mono({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});

const SourGummy = Sour_Gummy({
    variable: "--font-geist-mono",
    subsets: ["latin"],
});


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={`${geistSans.variable} ${geistMono.variable} antialiased`}>

        <Header/>

        {children}
        </body>
        </html>
    );
}
